# Generated by Django 4.2.27 on 2026-01-13 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_sku_ca0cdc_idx',
            old_name='products_pr_sku_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_barcode_e44f4f_idx',
            old_name='products_pr_barcode_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_name_9ff0a3_idx',
            old_name='products_pr_name_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_is_acti_ca4d9a_idx',
            old_name='products_pr_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_categor_50f5f1_idx',
            old_name='products_pr_cat_act_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='products_pr_sku_dcab68_idx',
            old_name='products_pv_sku_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='products_pr_barcode_9a4ab3_idx',
            old_name='products_pv_barcode_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='products_pr_product_66459e_idx',
            old_name='products_pv_prod_act_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.ManyToManyField(blank=True, help_text='Available sizes for this product', related_name='products', to='products.size'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='low_stock_threshold',
            field=models.IntegerField(blank=True, default=10, help_text='Variant-specific low stock threshold', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
