# Generated by Django 4.2.27 on 2026-05-26 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_snapshot', models.CharField(blank=True, help_text='User.username at time of event, kept even if user is later deleted.', max_length=150)),
                ('action', models.CharField(db_index=True, max_length=32)),
                ('module', models.CharField(blank=True, db_index=True, help_text='Matches accounts.Permission.module values.', max_length=32)),
                ('object_type', models.CharField(blank=True, db_index=True, help_text="e.g. 'sales.Sale' or 'products.Product'.", max_length=64)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Optional diff or snapshot. Caller decides what to put here.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('path', models.CharField(blank=True, help_text='request.path at time of event.', max_length=255)),
                ('method', models.CharField(blank=True, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='Acting user; null for anonymous events (e.g. failed login).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='accounts_au_user_id_7b1069_idx'), models.Index(fields=['module', 'action', 'created_at'], name='accounts_au_module_ac63b8_idx'), models.Index(fields=['object_type', 'object_id'], name='accounts_au_object__353b30_idx')],
            },
        ),
    ]
