# Generated by Django 4.2.27 on 2026-01-19 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional cost for delivery', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_method',
            field=models.CharField(blank=True, help_text='Delivery method (pickup, delivery, etc.)', max_length=50, null=True),
        ),
    ]
