# Generated by Django 4.2.27 on 2026-01-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_add_delivery_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='shipping_address',
            field=models.TextField(blank=True, help_text='Shipping address for delivery', null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='shipping_location',
            field=models.CharField(blank=True, help_text='Shipping location/area', max_length=200, null=True),
        ),
    ]
