# Generated by Django 4.2.30 on 2026-05-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_holding_status_and_customer'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sale',
            new_name='sales_sale_status_fb684c_idx',
            old_name='sales_sale_status__a1b2c3_idx',
        ),
    ]
