# Generated by Django 4.2.27 on 2026-01-22 11:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_shipping_address_sale_shipping_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Customer wallet balance (positive = credit, negative = debt/amount owed)', max_digits=10),
        ),
    ]
