# Generated by Django 4.2.27 on 2026-01-22 12:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_customer_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Customer wallet balance (positive = credit, negative = debt/amount owed). Range: -9,999,999.99 to 9,999,999.99', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-9999999.99')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))]),
        ),
    ]
