# Generated by Django 4.2.30 on 2026-06-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_refunds'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sale',
            new_name='sales_sale_refund__c209d1_idx',
            old_name='sales_sale_refund__b8e2a1_idx',
        ),
    ]
