# Generated by Django 4.2.30 on 2026-06-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerwallettransaction',
            name='source_type',
            field=models.CharField(choices=[('overpayment', 'Overpayment from Sale'), ('debt', 'Unpaid Sale Balance'), ('debt_settlement', 'Debt Payment Received'), ('refund', 'Refund'), ('manual', 'Manual Adjustment'), ('payment', 'Payment from Wallet'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
