# Generated by Django 4.2.30 on 2026-06-30 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_sale_backfill_receipt_photo'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sale',
            new_name='sales_sale_occurre_f971c6_idx',
            old_name='sales_sale_occurre_91a2f1_idx',
        ),
        migrations.RenameIndex(
            model_name='sale',
            new_name='sales_sale_served__4372e6_idx',
            old_name='sales_sale_served__4c8e21_idx',
        ),
        migrations.RenameIndex(
            model_name='sale',
            new_name='sales_sale_entry_s_a4fc1d_idx',
            old_name='sales_sale_entry_s_7b3a44_idx',
        ),
    ]
