# Generated by Django 5.1.15 on 2026-10-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0016_merge_payment_reference_and_pending_approval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="entry_source",
            field=models.CharField(
                choices=[
                    ("pos", "POS"),
                    ("billing", "Billing"),
                    ("normal", "Normal sale"),
                    ("backfill", "Past sale entry"),
                    ("field", "Field sale"),
                ],
                db_index=True,
                default="pos",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="status",
            field=models.CharField(
                choices=[
                    ("holding", "Holding"),
                    ("pending_approval", "Pending approval"),
                    ("awaiting_payment", "Awaiting payment"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="completed",
                help_text="Holding = draft at the register; pending_approval = waiting for a manager; awaiting_payment = approved, collect funds; completed = stock moved and sale finalised.",
                max_length=20,
            ),
        ),
    ]
