# Generated by Django 4.2.27 on 2026-01-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='branch',
            new_name='settings_br_tenant__106b6a_idx',
            old_name='settings_br_tenant_branch_idx',
        ),
        migrations.RenameIndex(
            model_name='branch',
            new_name='settings_br_tenant__dd3141_idx',
            old_name='settings_br_tenant_name_idx',
        ),
        migrations.RenameIndex(
            model_name='branch',
            new_name='settings_br_is_acti_349c78_idx',
            old_name='settings_br_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='branch',
            new_name='settings_br_is_head_6bf409_idx',
            old_name='settings_br_is_head_idx',
        ),
        migrations.RenameIndex(
            model_name='tenant',
            new_name='settings_te_code_d7527b_idx',
            old_name='settings_te_code_idx',
        ),
        migrations.RenameIndex(
            model_name='tenant',
            new_name='settings_te_name_08b3da_idx',
            old_name='settings_te_name_idx',
        ),
        migrations.RenameIndex(
            model_name='tenant',
            new_name='settings_te_is_acti_a25f30_idx',
            old_name='settings_te_is_acti_idx',
        ),
    ]
