# Generated by Django 4.2.27 on 2026-01-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='branch',
            new_name='settings_br_tenant__106b6a_idx',
            old_name='settings_br_tenant_branch_idx',
        ),
        migrations.RenameIndex(
            model_name='branch',
            new_name='settings_br_tenant__dd3141_idx',
            old_name='settings_br_tenant_name_idx',
        ),
        migrations.RenameIndex(
            model_name='branch',
            new_name='settings_br_is_acti_349c78_idx',
            old_name='settings_br_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='branch',
            new_name='settings_br_is_head_6bf409_idx',
            old_name='settings_br_is_head_idx',
        ),
        migrations.RenameIndex(
            model_name='tenant',
            new_name='settings_te_code_d7527b_idx',
            old_name='settings_te_code_idx',
        ),
        migrations.RenameIndex(
            model_name='tenant',
            new_name='settings_te_name_08b3da_idx',
            old_name='settings_te_name_idx',
        ),
        migrations.RenameIndex(
            model_name='tenant',
            new_name='settings_te_is_acti_a25f30_idx',
            old_name='settings_te_is_acti_idx',
        ),
        migrations.AlterField(
            model_name='modulesettings',
            name='module_name',
            field=models.CharField(choices=[('products', 'Products Management'), ('sales', 'Sales'), ('customers', 'Customer Management'), ('suppliers', 'Supplier Management'), ('employees', 'Employee Management'), ('invoicing', 'Invoicing'), ('inventory', 'Inventory Management'), ('stock', 'Stock Management'), ('expenses', 'Expenses'), ('income', 'Income'), ('bank_accounts', 'Bank Accounts'), ('money_transfer', 'Money Transfer'), ('accounting', 'Accounting'), ('balance_sheet', 'Balance Sheet'), ('trial_balance', 'Trial Balance'), ('cash_flow', 'Cash Flow'), ('account_statement', 'Account Statement'), ('barcodes', 'Barcodes'), ('reports', 'Reports'), ('settings', 'System Settings')], max_length=50, unique=True),
        ),
    ]
