# Generated by Django 4.2.30 on 2026-05-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_modulesetting'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='modulesetting',
            new_name='settings_mo_module_66f04d_idx',
            old_name='settings_mo_module_8a1f2d_idx',
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='hide_entity_status_toggles',
            field=models.BooleanField(default=False, help_text='Store-wide override: hides active/inactive UI for products, customers, employees, suppliers, users, and categories. Module status flags are ignored while this is on.'),
        ),
    ]
