# Generated by Django 4.2.30 on 2026-06-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_storesettings_sales_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='maker_checker_sales_controls',
            field=models.BooleanField(default=False, help_text='Optional: post-completion sale edits via maker-checker (notes/payment method only). Off by default — POS and checkout are unchanged.'),
        ),
    ]
