# Generated by Django 4.2.30 on 2026-06-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_alter_storesettings_maker_checker_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='maker_checker_enabled',
            field=models.BooleanField(default=False, help_text='Require checker approval before sensitive price/stock/settings changes go live'),
        ),
    ]
