# Generated by Django 5.1.15 on 2026-10-05 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_fieldorderline_variant"),
        ("sales", "0017_field_sales"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldorder",
            name="sale",
            field=models.OneToOneField(
                blank=True,
                help_text="Sale recorded for the agent when the order was packed",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="field_order",
                to="sales.sale",
            ),
        ),
    ]
