# Generated by Django 4.2.27 on 2026-01-17 13:47

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Supplier name or company name', max_length=200)),
                ('supplier_code', models.CharField(db_index=True, editable=False, help_text='Unique supplier code', max_length=50, unique=True)),
                ('supplier_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business'), ('manufacturer', 'Manufacturer'), ('distributor', 'Distributor'), ('wholesaler', 'Wholesaler')], default='business', max_length=20)),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person name', max_length=200)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20)),
                ('alternate_phone', models.CharField(blank=True, help_text='Alternate phone number', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, help_text='State or Province', max_length=100)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('tax_id', models.CharField(blank=True, help_text='Tax ID or VAT number', max_length=50)),
                ('registration_number', models.CharField(blank=True, help_text='Business registration number', max_length=100)),
                ('website', models.URLField(blank=True, help_text='Company website')),
                ('payment_terms', models.CharField(choices=[('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('net_60', 'Net 60'), ('cod', 'Cash on Delivery'), ('prepaid', 'Prepaid'), ('custom', 'Custom Terms')], default='net_30', help_text='Default payment terms', max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Credit limit (0 means no credit limit)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('account_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current account balance (amount owed to supplier)', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the supplier')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, help_text='Supplier rating (1-5)')),
                ('is_preferred', models.BooleanField(default=False, help_text='Mark as preferred supplier')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this supplier is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='suppliers_s_name_6277a9_idx'), models.Index(fields=['supplier_code'], name='suppliers_s_supplie_97d6e1_idx'), models.Index(fields=['email'], name='suppliers_s_email_971388_idx'), models.Index(fields=['phone'], name='suppliers_s_phone_af9b45_idx'), models.Index(fields=['is_active'], name='suppliers_s_is_acti_a75d30_idx'), models.Index(fields=['supplier_type'], name='suppliers_s_supplie_c9bf31_idx')],
            },
        ),
    ]
