# Generated by Django 4.2.27 on 2026-01-13 14:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='moneytransfer',
            new_name='transfers_m_transfe_f6593a_idx',
            old_name='transfers_mt_date_idx',
        ),
        migrations.RenameIndex(
            model_name='moneytransfer',
            new_name='transfers_m_status_59737c_idx',
            old_name='transfers_mt_status_idx',
        ),
        migrations.RenameIndex(
            model_name='moneytransfer',
            new_name='transfers_m_from_ac_5afec1_idx',
            old_name='transfers_mt_accounts_idx',
        ),
        migrations.AlterField(
            model_name='moneytransfer',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
