# Generated by Django 4.2.30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daily_notes', '0003_dailytask_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynote',
            name='is_sticky',
            field=models.BooleanField(
                default=False,
                help_text='Sticky notes block the assignee until they are ticked.',
            ),
        ),
        migrations.AddField(
            model_name='dailynote',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailynote',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailynote',
            name='assigned_to',
            field=models.ForeignKey(
                blank=True,
                help_text='Staff member who must resolve a sticky note.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_daily_notes',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelOptions(
            name='dailynote',
            options={'ordering': ['-is_sticky', 'is_done', '-note_date', '-created_at']},
        ),
        migrations.AddIndex(
            model_name='dailynote',
            index=models.Index(
                fields=['assigned_to', 'is_sticky', 'is_done'],
                name='daily_notes_assigne_sticky_idx',
            ),
        ),
    ]
