# Generated by Django 4.2.30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('daily_notes', '0004_dailynote_sticky'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynote',
            name='assigned_role',
            field=models.ForeignKey(
                blank=True,
                help_text='When set, a copy is created for every active user with this role.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='daily_notes',
                to='accounts.role',
            ),
        ),
        migrations.AddField(
            model_name='dailynote',
            name='assignment_group',
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text='Shared id for notes fanned out to a role.',
                null=True,
            ),
        ),
    ]
