# Generated by Django 4.2.27 on 2026-01-19 07:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bankaccount',
            new_name='bankaccount_account_03af68_idx',
            old_name='bankaccount_account_num_idx',
        ),
        migrations.RenameIndex(
            model_name='bankaccount',
            new_name='bankaccount_is_acti_243679_idx',
            old_name='bankaccount_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='banktransaction',
            new_name='bankaccount_transac_b83dde_idx',
            old_name='bankaccount_bt_date_idx',
        ),
        migrations.RenameIndex(
            model_name='banktransaction',
            new_name='bankaccount_bank_ac_213105_idx',
            old_name='bankaccount_bt_acc_date_idx',
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
