# Generated by Django 4.2.30 on 2026-06-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pendingchange',
            new_name='approvals_p_status_4367f6_idx',
            old_name='approvals_p_status_8a0f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='pendingchange',
            new_name='approvals_p_entity__679ca7_idx',
            old_name='approvals_p_entity_66f04d_idx',
        ),
        migrations.RenameIndex(
            model_name='pendingchange',
            new_name='approvals_p_batch_i_845a58_idx',
            old_name='approvals_p_batch_12ab34_idx',
        ),
        migrations.AlterField(
            model_name='pendingchange',
            name='apply_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Extra data needed to apply on approval (e.g. stock movement params).'),
        ),
    ]
