# Generated by Django 4.2.27 on 2026-01-19 07:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='income',
            new_name='income_inco_income__3ca912_idx',
            old_name='income_inco_inc_date_idx',
        ),
        migrations.RenameIndex(
            model_name='income',
            new_name='income_inco_status_522861_idx',
            old_name='income_inco_status_idx',
        ),
        migrations.RenameIndex(
            model_name='income',
            new_name='income_inco_categor_fa8ea0_idx',
            old_name='income_inco_cat_date_idx',
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
