# Generated by Django 4.2.27 on 2026-01-13 14:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='account',
            new_name='accounting__account_6b3bad_idx',
            old_name='accounting_account_code_idx',
        ),
        migrations.RenameIndex(
            model_name='account',
            new_name='accounting__account_1a6511_idx',
            old_name='accounting_account_type_idx',
        ),
        migrations.RenameIndex(
            model_name='account',
            new_name='accounting__is_acti_28dd04_idx',
            old_name='accounting_account_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='accounting__entry_d_79c286_idx',
            old_name='accounting_je_entry_date_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='accounting__account_0b3638_idx',
            old_name='accounting_je_account_date_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='accounting__referen_4bf694_idx',
            old_name='accounting_je_ref_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='accounting__transac_0accd6_idx',
            old_name='accounting_txn_date_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='accounting__referen_b49ec2_idx',
            old_name='accounting_txn_ref_idx',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
