# Generated by Django 5.1.15 on 2026-09-14 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "sales",
            "0010_rename_sales_sale_occurre_91a2f1_idx_sales_sale_occurre_f971c6_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_uuid",
                    models.UUIDField(blank=True, db_index=True, null=True, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("phone", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("prompted", "Prompted"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=20,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("pos", "POS"),
                            ("debt", "Debt settle"),
                            ("delivery", "Delivery collect"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("customer_name", models.CharField(blank=True, max_length=200)),
                ("invoice_number", models.CharField(blank=True, max_length=50)),
                (
                    "public_token",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "checkout_request_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("merchant_request_id", models.CharField(blank=True, max_length=64)),
                ("mpesa_receipt", models.CharField(blank=True, max_length=64)),
                ("failure_reason", models.TextField(blank=True)),
                ("callback_payload", models.JSONField(blank=True, null=True)),
                ("callback_processed", models.BooleanField(default=False)),
                ("sms_queued", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prompted_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_intents_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_intents",
                        to="sales.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
