# Generated by Django 4.2.27 on 2026-01-19 07:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_expense_cf8a73_idx',
            old_name='expenses_ex_exp_date_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_status_cbb790_idx',
            old_name='expenses_ex_status_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_categor_6b4e94_idx',
            old_name='expenses_ex_cat_date_idx',
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
