"""
Canonical per-module configuration keys (feature flags with typed JSON values).

Seeded by ``init_module_settings`` on fresh installs (also invoked from ``init_modules``).

Two configuration layers:
  * **StoreSettings** (singleton) — receipt, payments, catalog rules, and store-wide UI overrides.
  * **ModuleSetting** (this registry) — per-module display/workflow toggles under System Settings.

Install-level **ModuleFeature** flags (Module Settings page) still gate whether a capability
exists at all; keys here fine-tune behaviour for stores that have the module installed.
"""

from __future__ import annotations

from typing import Any


def _setting(
    key: str,
    label: str,
    description: str = '',
    default_value: Any = True,
    display_order: int = 0,
    impact: str | None = None,
):
    entry = {
        'key': key,
        'label': label,
        'description': description,
        'default_value': default_value,
        'display_order': display_order,
    }
    if impact:
        entry['impact'] = impact
    return entry


MODULE_SETTING_DEFINITIONS: dict[str, list[dict[str, Any]]] = {
    'products': [
        _setting(
            'show_status',
            'Show product status',
            'When off, hides status on the product list and form. Inactive products remain in the database and stay available for sales.',
            True,
            1,
        ),
        _setting(
            'show_cost_price',
            'Show cost price',
            'Hides cost on the product list and edit form. Cost is still stored for margin reports.',
            True,
            2,
        ),
        _setting(
            'show_mrp',
            'Show MRP (list price)',
            'Hides the maximum retail price column and field for stores that only use a single selling price.',
            True,
            3,
        ),
        _setting(
            'show_sku_in_list',
            'Show SKU in product list',
            'Displays SKU under the product name in the catalog table.',
            False,
            4,
        ),
        _setting(
            'show_low_stock_badges',
            'Show low-stock badges',
            'Shows warning badges on products at or below their low-stock threshold.',
            True,
            5,
        ),
        _setting(
            'enable_bulk_operations',
            'Bulk select and actions',
            'Enables row checkboxes and bulk activate, deactivate, and delete.',
            True,
            10,
            impact='high',
        ),
        _setting(
            'enable_csv_import_export',
            'CSV import and export',
            'Enables exporting the catalog and importing updates from a spreadsheet.',
            True,
            11,
        ),
        _setting(
            'allow_sales_catalog_access',
            'Sales: access Products & Categories',
            'Lets sales staff open the catalog screens. Also requires Store settings → Allow sales to add products.',
            True,
            20,
            impact='high',
        ),
        _setting(
            'allow_sales_edit_catalog_details',
            'Sales: edit catalog details',
            'Name, description, category, barcode, unit, and image — not price, cost, or stock.',
            True,
            21,
        ),
        _setting(
            'allow_sales_edit_pricing',
            'Sales: set selling price / MRP',
            'When off, sales cannot change prices; managers or admin set pricing later.',
            False,
            22,
            impact='high',
        ),
        _setting(
            'allow_sales_edit_cost',
            'Sales: set cost of goods',
            'When off, cost is hidden from sales and cannot be saved.',
            False,
            23,
            impact='high',
        ),
        _setting(
            'allow_sales_edit_stock',
            'Sales: set stock levels',
            'When off, sales cannot change quantity on hand or stock thresholds.',
            False,
            24,
            impact='high',
        ),
        _setting(
            'allow_manager_edit_pricing',
            'Managers: set selling price / MRP',
            'When off, only Super Admin can change product prices.',
            True,
            25,
            impact='high',
        ),
        _setting(
            'allow_manager_edit_cost',
            'Managers: set cost of goods',
            'When off, only Super Admin can enter or change product cost (default).',
            False,
            26,
            impact='high',
        ),
    ],
    'sales': [
        _setting(
            'show_discount',
            'Show discounts at checkout',
            'Hides discount fields on POS and billing checkout. Discount amounts sent by clients are rejected.',
            True,
            1,
            impact='high',
        ),
        _setting(
            'show_tax',
            'Show tax at checkout',
            'Hides tax percentage and amount on checkout screens.',
            True,
            2,
        ),
        _setting(
            'show_delivery',
            'Show delivery options',
            'Hides delivery toggle and delivery fee on checkout.',
            True,
            3,
        ),
        _setting(
            'require_customer',
            'Require customer on every sale',
            'Walk-in checkout is not allowed — cashier must select a registered customer.',
            False,
            4,
            impact='high',
        ),
        _setting(
            'allow_partial_payment',
            'Allow partial payment (debt)',
            'When off, the customer must pay the full total. Partial payment dialogs are disabled.',
            True,
            5,
            impact='high',
        ),
        _setting(
            'allow_excess_to_wallet',
            'Allow excess payment to wallet',
            'When off, overpayment can only be returned as change, not credited to wallet.',
            True,
            6,
        ),
        _setting(
            'validate_stock_before_sale',
            'Validate stock before sale',
            'When off, sales can proceed even when quantity exceeds on-hand stock (use with caution).',
            True,
            7,
            impact='high',
        ),
    ],
    'inventory': [
        _setting(
            'show_stock_movements',
            'Show stock movements',
            'Hides the movements list and product stock history. Purchases and sales still update stock.',
            True,
            1,
        ),
        _setting(
            'enable_stock_adjustments',
            'Allow stock adjustments',
            'Enables manual quantity corrections (positive or negative).',
            True,
            2,
        ),
        _setting(
            'enable_stock_purchases',
            'Allow stock purchases',
            'Enables recording incoming stock / purchase receipts.',
            True,
            3,
        ),
        _setting(
            'enable_stock_transfers',
            'Allow stock transfers',
            'Enables moving stock between branches.',
            True,
            4,
        ),
        _setting(
            'show_low_stock_alerts',
            'Show low-stock alerts',
            'Shows the low-stock tab and related API endpoints.',
            True,
            5,
        ),
        _setting(
            'show_out_of_stock_alerts',
            'Show out-of-stock alerts',
            'Shows the out-of-stock tab and related API endpoints.',
            True,
            6,
        ),
        _setting(
            'enable_inventory_report',
            'Show inventory overview report',
            'Shows valuation and movement summary cards on the Overview tab.',
            True,
            7,
        ),
        _setting(
            'show_movement_cost',
            'Show movement cost columns',
            'Hides unit cost and total cost on movement lists and history.',
            True,
            8,
        ),
        _setting(
            'allow_movement_undo',
            'Allow undo on transfers',
            'When off, reversing a stock transfer from the UI is disabled.',
            True,
            9,
        ),
    ],
    'customers': [
        _setting(
            'show_customer_code',
            'Show customer code',
            'Displays the auto-generated customer code under the name in lists.',
            True,
            1,
        ),
        _setting(
            'show_outstanding_balance',
            'Show outstanding balance',
            'Shows invoice balance owing on the customer list and summary cards.',
            True,
            2,
        ),
        _setting(
            'show_wallet_balance',
            'Show wallet balance',
            'Shows wallet credit or POS debt on the Customers page and at checkout.',
            True,
            3,
        ),
        _setting(
            'enable_wallet_payment',
            'Allow wallet debt payments',
            'When off, staff cannot record standalone payments against customer wallet debt.',
            True,
            9,
        ),
        _setting(
            'enable_customer_create',
            'Allow creating customers',
            'When off, new customers cannot be added from the Customers page or API.',
            True,
            10,
            impact='high',
        ),
        _setting(
            'enable_customer_edit',
            'Allow editing customers',
            'When off, existing customer records cannot be updated.',
            True,
            11,
            impact='high',
        ),
        _setting(
            'enable_customer_delete',
            'Allow deleting customers',
            'When off, customers cannot be removed from the catalog (sales history is kept).',
            True,
            12,
            impact='high',
        ),
        _setting(
            'show_customer_type',
            'Show customer type',
            'Shows Individual / Business type on the form and list.',
            True,
            4,
        ),
        _setting(
            'show_tax_id',
            'Show tax ID field',
            'Shows VAT / tax registration on the customer form.',
            True,
            5,
        ),
        _setting(
            'show_customer_notes',
            'Show notes field',
            'Shows internal notes on the customer form.',
            True,
            6,
        ),
        _setting(
            'show_customer_status',
            'Show active status',
            'Shows active/inactive badge and toggle on the customer form.',
            True,
            7,
        ),
        _setting(
            'allow_quick_add_at_pos',
            'Quick-add customer at POS',
            'Shows “Add new customer” in POS and billing checkout pickers (requires create enabled).',
            True,
            8,
        ),
    ],
    'daily_notes': [
        _setting(
            'allow_sales_access',
            'Sales: use daily notes',
            'Lets sales staff open the journal and add their own day notes.',
            True,
            1,
            impact='high',
        ),
        _setting(
            'allow_manager_view_all',
            'Managers: view all staff notes',
            'Managers see notes from every user, not only their own.',
            True,
            2,
            impact='high',
        ),
        _setting(
            'allow_sales_view_all',
            'Sales: view all staff notes',
            'When on, sales can read everyone’s notes (off by default). Grant via custom roles later.',
            False,
            3,
            impact='high',
        ),
    ],
    'employees': [
        _setting(
            'show_employee_id',
            'Show employee ID',
            'Displays the unique employee ID in lists and forms.',
            True,
            1,
        ),
        _setting(
            'show_salary',
            'Show salary',
            'Shows monthly salary on employee records (sensitive — off by default).',
            False,
            2,
        ),
        _setting(
            'show_department',
            'Show department',
            'Shows department filter, column, and form field.',
            True,
            3,
        ),
        _setting(
            'show_contact_details',
            'Show contact details',
            'Shows email, phone, and address fields.',
            True,
            4,
        ),
        _setting(
            'show_employee_notes',
            'Show notes',
            'Shows internal notes on the employee form.',
            True,
            5,
        ),
        _setting(
            'show_employee_status',
            'Show employment status',
            'Shows active / inactive / on leave / terminated status.',
            True,
            6,
        ),
        _setting(
            'enable_employee_create',
            'Allow creating employees',
            'When off, new employee records cannot be added.',
            True,
            10,
            impact='high',
        ),
        _setting(
            'enable_employee_edit',
            'Allow editing employees',
            'When off, existing employee records cannot be updated.',
            True,
            11,
            impact='high',
        ),
        _setting(
            'enable_employee_delete',
            'Allow deleting employees',
            'When off, employee records cannot be removed.',
            True,
            12,
            impact='high',
        ),
        _setting(
            'enable_employee_statistics',
            'Show employee statistics',
            'Shows summary cards on the Employees page.',
            True,
            7,
        ),
    ],
    'suppliers': [
        _setting(
            'show_supplier_code',
            'Show supplier code',
            'Displays auto-generated supplier code in lists.',
            True,
            1,
        ),
        _setting(
            'show_supplier_type',
            'Show supplier type',
            'Shows type column, filter, and form field.',
            True,
            2,
        ),
        _setting(
            'show_contact_details',
            'Show contact details',
            'Contact person, email, phone, and address fields.',
            True,
            3,
        ),
        _setting(
            'show_business_details',
            'Show business registration',
            'Tax ID, registration number, and website fields.',
            True,
            4,
        ),
        _setting(
            'show_payment_terms',
            'Show payment terms',
            'Default payment terms on supplier records.',
            True,
            5,
        ),
        _setting(
            'show_credit_fields',
            'Show credit and balance',
            'Credit limit, account balance, and related summary stats.',
            True,
            6,
        ),
        _setting(
            'show_supplier_rating',
            'Show supplier rating',
            'Star rating column and form field.',
            True,
            7,
        ),
        _setting(
            'show_preferred_flag',
            'Show preferred supplier flag',
            'Preferred badge and toggle on supplier records.',
            True,
            8,
        ),
        _setting(
            'show_supplier_notes',
            'Show notes',
            'Internal notes on the supplier form.',
            True,
            9,
        ),
        _setting(
            'show_supplier_status',
            'Show active status',
            'Active/inactive badge, filter, and form toggle.',
            True,
            10,
        ),
        _setting(
            'enable_supplier_create',
            'Allow creating suppliers',
            'When off, new suppliers cannot be added.',
            True,
            20,
            impact='high',
        ),
        _setting(
            'enable_supplier_edit',
            'Allow editing suppliers',
            'When off, existing suppliers cannot be updated.',
            True,
            21,
            impact='high',
        ),
        _setting(
            'enable_supplier_delete',
            'Allow deleting suppliers',
            'When off, suppliers cannot be removed.',
            True,
            22,
            impact='high',
        ),
        _setting(
            'enable_supplier_statistics',
            'Show supplier statistics',
            'Summary cards on the Suppliers page.',
            True,
            11,
        ),
        _setting(
            'enable_supplier_products',
            'Allow supplier product list',
            'API to list products linked to a supplier.',
            True,
            12,
        ),
    ],
    'reports': [
        _setting(
            'enable_dashboard_summary',
            'Dashboard summary report',
            'KPI bundle on the home dashboard (revenue, stock alerts, profit estimate).',
            True,
            1,
        ),
        _setting(
            'enable_sales_reports',
            'Sales reports',
            'Sales overview tile and detailed sales report.',
            True,
            2,
        ),
        _setting(
            'enable_product_reports',
            'Product reports',
            'Top products tile and product sales report.',
            True,
            3,
        ),
        _setting(
            'enable_inventory_reports',
            'Inventory reports',
            'Inventory health tile, stock report, and purchase report.',
            True,
            4,
        ),
        _setting(
            'enable_financial_reports',
            'Financial reports',
            'Expense, income, tax, profit & loss, and annual reports.',
            True,
            5,
        ),
        _setting(
            'enable_invoice_reports',
            'Invoice / AR reports',
            'Invoice report and customer outstanding tile.',
            True,
            6,
        ),
        _setting(
            'enable_supplier_reports',
            'Supplier reports',
            'Purchases grouped by supplier.',
            True,
            7,
        ),
        _setting(
            'enable_customer_reports',
            'Customer reports',
            'Customer purchase and outstanding summaries.',
            True,
            8,
        ),
        _setting(
            'enable_cash_reports',
            'Cash and payment reports',
            'Cash & payments hub tile and payment-method breakdown.',
            True,
            9,
        ),
        _setting(
            'show_discount_in_reports',
            'Show discount in reports',
            'Includes discount totals on sales reports and hub tiles.',
            True,
            10,
        ),
        _setting(
            'show_tax_in_reports',
            'Show tax in reports',
            'Includes tax totals and tax breakdown sections.',
            True,
            11,
        ),
        _setting(
            'show_cost_and_profit',
            'Show cost and profit metrics',
            'Shows inventory value, purchase costs, and profit estimates.',
            True,
            12,
        ),
        _setting(
            'show_legacy_report_catalog',
            'Show full report catalog',
            'Link to the classic all-reports list from the Reports hub.',
            True,
            13,
        ),
    ],
    'users': [
        _setting(
            'show_user_email',
            'Show email',
            'Email column on the users list and field on the user form.',
            True,
            1,
        ),
        _setting(
            'show_user_phone',
            'Show phone number',
            'Phone field on the user form.',
            True,
            2,
        ),
        _setting(
            'show_user_full_name',
            'Show full name',
            'First and last name columns and form fields.',
            True,
            3,
        ),
        _setting(
            'show_user_status',
            'Show active status',
            'Status badge, filter, and active toggle on user records.',
            True,
            4,
        ),
        _setting(
            'show_date_joined',
            'Show date joined',
            'Joined date column on the users list.',
            True,
            5,
        ),
        _setting(
            'show_user_statistics',
            'Show user statistics',
            'Summary cards on the Users page.',
            True,
            6,
        ),
        _setting(
            'show_staff_flag',
            'Show staff member flag',
            'Staff checkbox on the user form (Django admin access).',
            True,
            7,
        ),
        _setting(
            'enable_user_create',
            'Allow creating users',
            'When off, new users cannot be added.',
            True,
            20,
            impact='high',
        ),
        _setting(
            'enable_user_edit',
            'Allow editing users',
            'When off, admins cannot update other users (self-service still works).',
            True,
            21,
            impact='high',
        ),
        _setting(
            'enable_user_delete',
            'Allow deleting users',
            'When off, users cannot be removed.',
            True,
            22,
            impact='high',
        ),
        _setting(
            'enable_inline_role_assignment',
            'Allow inline role assignment',
            'Role dropdown on the users list and assign-role API.',
            True,
            23,
            impact='high',
        ),
        _setting(
            'enable_role_create',
            'Allow creating roles',
            'When off, new custom roles cannot be added.',
            True,
            30,
            impact='high',
        ),
        _setting(
            'enable_role_edit',
            'Allow editing roles',
            'When off, existing roles and their permissions cannot be changed.',
            True,
            31,
            impact='high',
        ),
        _setting(
            'enable_role_delete',
            'Allow deleting roles',
            'When off, custom roles cannot be removed.',
            True,
            32,
            impact='high',
        ),
        _setting(
            'enable_permission_catalog',
            'Show permission catalog',
            'Permission picker when editing roles. When off, roles can still exist but permissions cannot be browsed.',
            True,
            33,
        ),
    ],
}
