# Generated by Django 4.2.27 on 2026-01-19 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='inventory_s_product_5919a9_idx',
            old_name='inventory_sm_prod_created_idx',
        ),
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='inventory_s_movemen_ed5291_idx',
            old_name='inventory_sm_type_created_idx',
        ),
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='inventory_s_created_05ebf5_idx',
            old_name='inventory_sm_created_idx',
        ),
    ]
