# Generated by Django 4.2.27 on 2026-01-19 07:23

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Unique employee ID', max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('position', models.CharField(help_text='Job title/position', max_length=100)),
                ('department', models.CharField(choices=[('production', 'Production'), ('sales', 'Sales'), ('admin', 'Administration'), ('finance', 'Finance'), ('management', 'Management'), ('other', 'Other')], default='other', max_length=50)),
                ('hire_date', models.DateField(help_text='Date of hire')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly salary', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the employee')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee_id'], name='employees_e_employe_514cc5_idx'), models.Index(fields=['status'], name='employees_e_status_61c2f6_idx'), models.Index(fields=['department'], name='employees_e_departm_e28f46_idx')],
            },
        ),
    ]
