# Generated by Django 4.2.30 on 2026-09-14 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idempotency', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='idempotencyrecord',
            new_name='idempotency_key_b0320f_idx',
            old_name='idempotency_key_user_idx',
        ),
    ]
